from __future__ import annotations

import argparse
import json
import logging
import os
import uuid
from pathlib import Path
from urllib.parse import urlparse

import chromadb

from embeddings import get_embedding_model
from settings import (
    acquire_ingestion_lock,
    get_settings,
    hash_collection_snapshot,
    release_ingestion_lock,
    snapshot_input,
)

LOGGER = logging.getLogger(__name__)


def default_input_path() -> Path:
    script_path = Path(__file__).resolve()
    candidates: list[Path] = []

    if len(script_path.parents) >= 3:
        candidates.append(
            script_path.parents[2] / "ocr_pipeline" / "chroma_chunks.jsonl"
        )

    candidates.append(Path("/data/ocr_pipeline/chroma_chunks.jsonl"))

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return candidates[0]


def parse_args() -> argparse.Namespace:
    settings = get_settings()
    input_default = default_input_path()

    parser = argparse.ArgumentParser(
        description="Embed OCR chunks and upsert them into a Chroma collection."
    )
    parser.add_argument(
        "--input-path",
        type=Path,
        default=input_default,
        help="Path to chroma_chunks.jsonl generated by the OCR pipeline.",
    )
    parser.add_argument(
        "--collection-name",
        default=settings.chroma_collection_name,
        help="Target Chroma collection name.",
    )
    parser.add_argument(
        "--embedding-model",
        default=settings.embedding_model_name,
        help="FastEmbed model name for embeddings.",
    )
    parser.add_argument(
        "--chroma-api-url",
        default=settings.chroma_api_url,
        help="Base URL for the Chroma HTTP server.",
    )
    parser.add_argument(
        "--chroma-auth-token",
        default=settings.chroma_auth_token,
        help="Optional Chroma auth token.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=64,
        help="Number of chunks to embed and upsert per batch.",
    )
    parser.add_argument(
        "--lock-path",
        type=Path,
        default=Path(
            os.getenv(
                "INGESTION_LOCK_PATH",
                "/run/private-analyst-locks/ingest.lock",
            )
        ),
        help="Shared lock file used to serialize ingestion and fail serving closed.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional limit for smoke-test ingestion runs.",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging verbosity.",
    )
    return parser.parse_args()


def configure_logging(log_level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, log_level),
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def create_chroma_client(
    chroma_api_url: str, chroma_auth_token: str
) -> chromadb.HttpClient:
    parsed = urlparse(chroma_api_url)
    host = parsed.hostname or "chromadb"
    port = parsed.port or (443 if parsed.scheme == "https" else 8000)
    headers: dict[str, str] = {}
    if chroma_auth_token:
        headers["X-Chroma-Token"] = chroma_auth_token

    return chromadb.HttpClient(
        host=host,
        port=port,
        ssl=parsed.scheme == "https",
        headers=headers,
    )


def sanitize_metadata(raw_metadata: dict) -> dict:
    cleaned: dict[str, str | int | float | bool] = {}
    for key, value in raw_metadata.items():
        if value is None:
            continue
        if isinstance(value, (str, int, float, bool)):
            cleaned[key] = value
        else:
            cleaned[key] = str(value)
    return cleaned


def iter_rows(input_path: Path):
    with input_path.open("r", encoding="utf-8") as input_file:
        for line_number, line in enumerate(input_file, start=1):
            payload = json.loads(line)
            chunk_id = str(payload["id"])
            text = str(payload.get("text", "")).strip()
            metadata = payload.get("metadata") or {}
            if not text:
                LOGGER.debug("Skipping empty text row %d", line_number)
                continue
            yield chunk_id, text, sanitize_metadata(metadata)


def flush_batch(
    collection,
    embedding_model,
    batch: list[tuple[str, str, dict]],
) -> None:
    if not batch:
        return

    ids = [chunk_id for chunk_id, _, _ in batch]
    documents = [text for _, text, _ in batch]
    metadatas = [metadata for _, _, metadata in batch]
    embeddings = embedding_model.encode_passages(documents)

    collection.upsert(
        ids=ids,
        documents=documents,
        metadatas=metadatas,
        embeddings=embeddings,
    )


def _run_ingestion_snapshot(
    args: argparse.Namespace,
    input_path: Path,
    corpus_sha256: str,
) -> int:
    available_rows = sum(1 for _ in iter_rows(input_path))
    expected_rows = available_rows if args.limit is None else min(args.limit, available_rows)
    chroma_client = create_chroma_client(args.chroma_api_url, args.chroma_auth_token)
    collection = chroma_client.get_or_create_collection(name=args.collection_name)
    index_generation = uuid.uuid4().hex
    collection.modify(
        metadata={
            "embedding_model": args.embedding_model,
            "corpus_sha256": corpus_sha256,
            "index_rows": expected_rows,
            "index_state": "ingesting",
            "index_generation": index_generation,
        }
    )
    embedding_model = get_embedding_model(args.embedding_model)
    batch: list[tuple[str, str, dict]] = []
    desired_ids: set[str] = set()
    total_rows = 0

    for chunk_id, text, metadata in iter_rows(input_path):
        batch.append((chunk_id, text, metadata))
        desired_ids.add(chunk_id)
        total_rows += 1
        if args.limit is not None and total_rows >= args.limit:
            break
        if len(batch) >= args.batch_size:
            flush_batch(collection, embedding_model, batch)
            LOGGER.info("Upserted %d rows", total_rows)
            batch.clear()

    flush_batch(collection, embedding_model, batch)
    existing_ids = set(collection.get(include=[])["ids"])
    stale_ids = sorted(existing_ids - desired_ids)
    for start in range(0, len(stale_ids), args.batch_size):
        collection.delete(ids=stale_ids[start : start + args.batch_size])
    if collection.count() != expected_rows:
        raise RuntimeError("Chroma index inventory does not match the input snapshot.")
    metadata = {
        "embedding_model": args.embedding_model,
        "corpus_sha256": corpus_sha256,
        "index_rows": expected_rows,
        "index_state": "complete" if args.limit is None else "pilot",
        "index_generation": index_generation,
    }
    if args.limit is None:
        metadata["index_sha256"] = hash_collection_snapshot(collection)
    collection.modify(metadata=metadata)
    LOGGER.info(
        "Ingestion complete. Collection=%s | rows_upserted=%d",
        args.collection_name,
        total_rows,
    )
    return 0


def run_ingestion(args: argparse.Namespace) -> int:
    if not args.input_path.exists():
        raise FileNotFoundError(f"Input JSONL not found: {args.input_path}")
    lock_token = acquire_ingestion_lock(args.lock_path)
    snapshot_path: Path | None = None
    try:
        snapshot_path, corpus_sha256 = snapshot_input(args.input_path)
        return _run_ingestion_snapshot(args, snapshot_path, corpus_sha256)
    finally:
        if snapshot_path is not None:
            snapshot_path.unlink(missing_ok=True)
        release_ingestion_lock(args.lock_path, lock_token)


def main() -> int:
    args = parse_args()
    configure_logging(args.log_level)
    try:
        return run_ingestion(args)
    except Exception as exc:  # noqa: PERF203
        LOGGER.exception("Ingestion failed: %s", exc)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
