from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from urllib.parse import urlparse

import chromadb

from embeddings import get_embedding_model
from settings import get_settings

LOGGER = logging.getLogger(__name__)


def default_input_path() -> Path:
    script_path = Path(__file__).resolve()
    candidates: list[Path] = []

    if len(script_path.parents) >= 3:
        candidates.append(
            script_path.parents[2] / "ocr_pipeline" / "chroma_chunks.jsonl"
        )

    candidates.append(Path("/data/ocr_pipeline/chroma_chunks.jsonl"))

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return candidates[0]


def parse_args() -> argparse.Namespace:
    settings = get_settings()
    input_default = default_input_path()

    parser = argparse.ArgumentParser(
        description="Embed OCR chunks and upsert them into a Chroma collection."
    )
    parser.add_argument(
        "--input-path",
        type=Path,
        default=input_default,
        help="Path to chroma_chunks.jsonl generated by the OCR pipeline.",
    )
    parser.add_argument(
        "--collection-name",
        default=settings.chroma_collection_name,
        help="Target Chroma collection name.",
    )
    parser.add_argument(
        "--embedding-model",
        default=settings.embedding_model_name,
        help="FastEmbed model name for embeddings.",
    )
    parser.add_argument(
        "--chroma-api-url",
        default=settings.chroma_api_url,
        help="Base URL for the Chroma HTTP server.",
    )
    parser.add_argument(
        "--chroma-auth-token",
        default=settings.chroma_auth_token,
        help="Optional Chroma auth token.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=64,
        help="Number of chunks to embed and upsert per batch.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional limit for smoke-test ingestion runs.",
    )
    parser.add_argument(
        "--log-level",
        default="INFO",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging verbosity.",
    )
    return parser.parse_args()


def configure_logging(log_level: str) -> None:
    logging.basicConfig(
        level=getattr(logging, log_level),
        format="%(asctime)s | %(levelname)s | %(message)s",
    )


def create_chroma_client(
    chroma_api_url: str, chroma_auth_token: str
) -> chromadb.HttpClient:
    parsed = urlparse(chroma_api_url)
    host = parsed.hostname or "chromadb"
    port = parsed.port or (443 if parsed.scheme == "https" else 8000)
    headers: dict[str, str] = {}
    if chroma_auth_token:
        headers["X-Chroma-Token"] = chroma_auth_token

    return chromadb.HttpClient(
        host=host,
        port=port,
        ssl=parsed.scheme == "https",
        headers=headers,
    )


def sanitize_metadata(raw_metadata: dict) -> dict:
    cleaned: dict[str, str | int | float | bool] = {}
    for key, value in raw_metadata.items():
        if value is None:
            continue
        if isinstance(value, (str, int, float, bool)):
            cleaned[key] = value
        else:
            cleaned[key] = str(value)
    return cleaned


def iter_rows(input_path: Path):
    with input_path.open("r", encoding="utf-8") as input_file:
        for line_number, line in enumerate(input_file, start=1):
            payload = json.loads(line)
            chunk_id = str(payload["id"])
            text = str(payload.get("text", "")).strip()
            metadata = payload.get("metadata") or {}
            if not text:
                LOGGER.debug("Skipping empty text row %d", line_number)
                continue
            yield chunk_id, text, sanitize_metadata(metadata)


def flush_batch(
    collection, embedding_model, batch: list[tuple[str, str, dict]]
) -> None:
    if not batch:
        return

    ids = [chunk_id for chunk_id, _, _ in batch]
    documents = [text for _, text, _ in batch]
    metadatas = [metadata for _, _, metadata in batch]
    embeddings = embedding_model.encode_passages(documents)

    collection.upsert(
        ids=ids,
        documents=documents,
        metadatas=metadatas,
        embeddings=embeddings,
    )


def run_ingestion(args: argparse.Namespace) -> int:
    if not args.input_path.exists():
        raise FileNotFoundError(f"Input JSONL not found: {args.input_path}")

    chroma_client = create_chroma_client(args.chroma_api_url, args.chroma_auth_token)
    collection = chroma_client.get_or_create_collection(
        name=args.collection_name,
        metadata={"embedding_model": args.embedding_model},
    )
    embedding_model = get_embedding_model(args.embedding_model)

    batch: list[tuple[str, str, dict]] = []
    total_rows = 0

    for chunk_id, text, metadata in iter_rows(args.input_path):
        batch.append((chunk_id, text, metadata))
        total_rows += 1

        if args.limit is not None and total_rows >= args.limit:
            break

        if len(batch) >= args.batch_size:
            flush_batch(collection, embedding_model, batch)
            LOGGER.info("Upserted %d rows", total_rows)
            batch.clear()

    if batch:
        flush_batch(collection, embedding_model, batch)

    LOGGER.info(
        "Ingestion complete. Collection=%s | rows_upserted=%d",
        args.collection_name,
        total_rows,
    )
    return 0


def main() -> int:
    args = parse_args()
    configure_logging(args.log_level)
    try:
        return run_ingestion(args)
    except Exception as exc:  # noqa: PERF203
        LOGGER.exception("Ingestion failed: %s", exc)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
