"""Post-filter existing markdown_reports with the stricter, training-friendly rules.

This applies the same noise filters as ``export_markdown_reports.py`` to reports
that were generated by an earlier, looser version of the exporter, without having
to re-parse the original ``raw_dataset`` corpus (which takes hours).

It re-cleans every page body line-by-line, drops compliance/contact-only pages,
removes near-empty caption-only shells (``--min-doc-words``), de-duplicates
near-identical reports (e.g. PDF + PPTX + revised copies of the same document),
deletes the noise files, and rewrites ``manifest.jsonl``.

For a full, authoritative refresh from source, prefer re-running
``export_markdown_reports.py`` instead.
"""
from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path

try:
    from .export_markdown_reports import (
        clean_line,
        content_fingerprint,
        looks_like_heading,
        page_is_compliance,
    )
except ImportError:  # pragma: no cover - supports direct script execution
    from export_markdown_reports import (
        clean_line,
        content_fingerprint,
        looks_like_heading,
        page_is_compliance,
    )

LOGGER = logging.getLogger(__name__)
PAGE_SPLIT_RE = re.compile(r"(?m)^## Page \d+\s*$")
HEADER_SPLIT = "## Report Body"


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--reports-dir",
        type=Path,
        default=repo_root / "ocr_pipeline" / "markdown_reports",
        help="Directory of generated Markdown reports + manifest.jsonl.",
    )
    parser.add_argument("--min-page-words", type=int, default=20)
    parser.add_argument("--min-doc-words", type=int, default=80)
    parser.add_argument("--keep-duplicates", action="store_true")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Report what would change without deleting or rewriting files.",
    )
    parser.add_argument(
        "--log-level", default="INFO", choices=["DEBUG", "INFO", "WARNING", "ERROR"]
    )
    return parser.parse_args()


def reclean_page_block(block: str, min_page_words: int) -> str:
    """Re-clean a single ``## Page N`` body block; return '' if it is noise."""
    if page_is_compliance(block):
        return ""
    kept: list[str] = []
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped:
            kept.append("")
            continue
        # Preserve markdown table rows and existing headings verbatim.
        if stripped.startswith(("|", "### ", "## ")):
            kept.append(stripped)
            continue
        cleaned = clean_line(stripped)
        if cleaned:
            kept.append(cleaned)
    text = "\n".join(kept)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    if not text:
        return ""
    words = len(re.sub(r"\s+", " ", text).split())
    if words < min_page_words and not looks_like_heading(text):
        return ""
    return text


def reclean_report(markdown: str, min_page_words: int) -> tuple[str, int]:
    """Return (rebuilt_markdown, body_word_count); ('' , 0) if fully noise."""
    if HEADER_SPLIT not in markdown:
        return "", 0
    header, body = markdown.split(HEADER_SPLIT, 1)
    parts = PAGE_SPLIT_RE.split(body)
    page_numbers = PAGE_SPLIT_RE.findall(body)
    # parts[0] is preamble before first "## Page" marker (usually empty).
    page_bodies = parts[1:]

    rebuilt: list[str] = [header.rstrip(), HEADER_SPLIT]
    retained = 0
    body_words = 0
    for marker, block in zip(page_numbers, page_bodies):
        cleaned = reclean_page_block(block, min_page_words)
        if not cleaned:
            continue
        retained += 1
        body_words += len(re.sub(r"\s+", " ", cleaned).split())
        rebuilt.extend(["", marker, "", cleaned])

    if retained == 0:
        return "", 0
    return "\n".join(rebuilt).strip() + "\n", body_words


def load_manifest(reports_dir: Path) -> dict[str, dict]:
    manifest_path = reports_dir / "manifest.jsonl"
    by_path: dict[str, dict] = {}
    if not manifest_path.exists():
        return by_path
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        by_path[row.get("markdown_path", "")] = row
    return by_path


def clean_reports(args: argparse.Namespace) -> None:
    reports_dir: Path = args.reports_dir
    if not reports_dir.exists():
        raise FileNotFoundError(f"Reports directory does not exist: {reports_dir}")

    manifest = load_manifest(reports_dir)
    md_files = sorted(reports_dir.glob("*.md"))
    LOGGER.info("Scanning %d markdown reports in %s", len(md_files), reports_dir)

    seen_fingerprints: dict[str, str] = {}
    kept_rows: list[dict] = []
    deleted_empty = 0
    deleted_short = 0
    deleted_duplicate = 0
    rewritten = 0

    for md_path in md_files:
        original = md_path.read_text(encoding="utf-8")
        rebuilt, body_words = reclean_report(original, args.min_page_words)
        rel = md_path.name

        if not rebuilt:
            deleted_empty += 1
            if not args.dry_run:
                md_path.unlink()
            LOGGER.debug("delete (empty after re-clean): %s", rel)
            continue
        if body_words < args.min_doc_words:
            deleted_short += 1
            if not args.dry_run:
                md_path.unlink()
            LOGGER.debug("delete (body %d < %d): %s", body_words, args.min_doc_words, rel)
            continue

        fingerprint = content_fingerprint(rebuilt)
        if not args.keep_duplicates and fingerprint in seen_fingerprints:
            deleted_duplicate += 1
            if not args.dry_run:
                md_path.unlink()
            LOGGER.debug("delete (dup of %s): %s", seen_fingerprints[fingerprint], rel)
            continue
        seen_fingerprints[fingerprint] = rel

        if rebuilt != original and not args.dry_run:
            md_path.write_text(rebuilt, encoding="utf-8")
            rewritten += 1
        elif rebuilt != original:
            rewritten += 1

        row = manifest.get(rel, {}).copy()
        row.setdefault("markdown_path", rel)
        row["markdown_word_count"] = len(rebuilt.split())
        row["body_word_count"] = body_words
        row["content_fingerprint"] = fingerprint
        kept_rows.append(row)

    if not args.dry_run:
        manifest_path = reports_dir / "manifest.jsonl"
        with manifest_path.open("w", encoding="utf-8") as handle:
            for row in kept_rows:
                handle.write(json.dumps(row, ensure_ascii=False) + "\n")

    prefix = "[DRY-RUN] " if args.dry_run else ""
    LOGGER.info(
        "%skept=%d rewritten=%d | deleted: empty=%d short=%d duplicate=%d",
        prefix, len(kept_rows), rewritten, deleted_empty, deleted_short, deleted_duplicate,
    )


def main() -> int:
    args = parse_args()
    logging.basicConfig(
        level=getattr(logging, args.log_level),
        format="%(asctime)s | %(levelname)s | %(message)s",
    )
    try:
        clean_reports(args)
    except Exception as exc:  # noqa: PERF203
        LOGGER.error("Cleanup failed: %s", exc)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
